default: copilot

profiles:
  claude:
    agent: claude
    agent-args:
      - --allowedTools
      - "shell"
    nix:
      enable: auto
      mount-socket: true
    docker:
      mount-socket: true
    gcloud:
      mount-config: true
    aws:
      mount-config: true
    gpg:
      forward-agent: true

  copilot:
    agent: copilot
    agent-args:
      - "--yolo"
    nix:
      enable: auto
      mount-socket: true
    docker:
      mount-socket: true
    gcloud:
      mount-config: true
    aws:
      mount-config: true
