default: copilot-nix

profiles:
  claude-nix:
    agent: claude
    agent-args:
      - "--yolo"
    nix:
      enable: auto
      mount-socket: true
    docker:
      mount-socket: true

  copilot-nix:
    agent: copilot
    agent-args:
      - "--yolo"
    nix:
      enable: auto
      mount-socket: true
    docker:
      mount-socket: true
