/**
 * ACP clients stop agents by killing them: Emacs `delete-process` sends
 * SIGKILL to nas's process group, so no Scope finalizer runs and the session's
 * DinD sidecar, registry mirror, network and volumes stay behind.
 *
 * nas therefore starts a reaper in its own session, holding the write end of
 * the reaper's stdin. The pipe reaches EOF however nas ends, and the reaper
 * then removes that session's Docker resources. After a normal exit they are
 * already gone and every removal is a no-op.
 */

import { spawn } from "node:child_process";
import type { Readable } from "node:stream";
import { sessionDockerResources } from "../docker/nas_resources.ts";
import { reapSessionDockerResources } from "../docker/session_reaper.ts";
import { logDebug, logWarn } from "../log.ts";
import { resolveStableNasCommand } from "../ui/launch.ts";

export const ACP_REAPER_SUBCOMMAND = "__acp-reaper";

/** Only generated session ids name resources this reaper may remove. */
export function isReapableSessionId(sessionId: string): boolean {
  return /^sess_[0-9a-f]+$/.test(sessionId);
}

/** Resolve once the owner's end of the pipe is closed. */
export function awaitOwnerExit(input: Readable): Promise<void> {
  return new Promise((resolve) => {
    if (input.readableEnded || input.destroyed) {
      resolve();
      return;
    }
    input.once("end", () => resolve());
    input.once("close", () => resolve());
    input.once("error", () => resolve());
    // The owner never writes; drain anyway so EOF is observed.
    input.resume();
  });
}

export interface AcpReaperCommand {
  readonly command: string;
  readonly args: readonly string[];
}

function defaultReaperCommand(sessionId: string): AcpReaperCommand | null {
  const nas = resolveStableNasCommand();
  if (!nas) return null;
  return {
    command: nas.nasBin,
    args: [...nas.nasArgs, ACP_REAPER_SUBCOMMAND, sessionId],
  };
}

export function spawnAcpSessionReaper(
  sessionId: string,
  command: AcpReaperCommand | null = defaultReaperCommand(sessionId),
): void {
  if (!isReapableSessionId(sessionId)) {
    logWarn(
      `[nas] ACP: session id ${sessionId} is not generated by nas; resources left by a killed client need \`nas container clean\``,
    );
    return;
  }
  if (!command) {
    logWarn(
      "[nas] ACP: no stable nas command for the session reaper; resources left by a killed client need `nas container clean`",
    );
    return;
  }
  try {
    const child = spawn(command.command, [...command.args], {
      // Own session: a process-group kill of nas must not reach the reaper.
      detached: true,
      stdio: ["pipe", "ignore", "ignore"],
    });
    child.once("error", (error) =>
      logWarn(`[nas] ACP: session reaper failed: ${error.message}`),
    );
    child.stdin?.on("error", () => {});
    // Neither the child nor the pipe may keep nas's event loop alive; the
    // write end stays open until nas itself exits.
    (child.stdin as { unref?: () => void } | null)?.unref?.();
    child.unref();
  } catch (error) {
    logWarn(
      `[nas] ACP: session reaper failed: ${error instanceof Error ? error.message : String(error)}`,
    );
  }
}

export async function runAcpReaperCommand(
  args: readonly string[],
  input: Readable = process.stdin,
): Promise<void> {
  const sessionId = args[0];
  if (!sessionId || !isReapableSessionId(sessionId)) {
    throw new Error(`${ACP_REAPER_SUBCOMMAND} requires a nas session id`);
  }
  await awaitOwnerExit(input);
  const steps = await reapSessionDockerResources(
    sessionDockerResources(sessionId),
  );
  for (const step of steps) {
    logDebug(
      `[nas] ACP reaper: ${step.action}${step.error ? ` (skipped: ${step.error})` : ""}`,
    );
  }
}
