/** Quote a value for a POSIX shell. */
export function shellQuote(value) {
  return `'${String(value).replace(/'/g, `'\\''`)}'`;
}

/**
 * The snippet Claude Code runs before each Bash command (CLAUDE_ENV_FILE).
 *
 * Inside the sandbox a command gets a fresh network namespace, where nothing
 * listens on the API address until a relay is started there. The snippet
 * compares namespaces before starting any process, so commands outside the
 * sandbox pay two file reads. It is read by bash and zsh alike, so it keeps
 * to POSIX syntax, survives `set -u`, and uses no globs. It prints nothing
 * on success: its output would land in the command's output.
 */
export function renderEnvFile({
  version,
  node,
  script,
  socket,
  api,
  instance,
  namePrefix,
  publishIp,
  baseNetnsFile,
}) {
  const ensure = [
    node,
    script,
    "ensure",
    "--socket",
    socket,
    "--instance",
    instance,
    "--name-prefix",
    namePrefix,
    "--api",
    api,
    ...(publishIp === undefined ? [] : ["--publish-ip", publishIp]),
  ]
    .map(shellQuote)
    .join(" ");
  return `# Generated by dind-bridge ${version} env-file. Point CLAUDE_ENV_FILE here.
# Starts this network namespace's Docker relay when a Bash command runs in
# Claude Code's sandbox. Prints nothing unless Docker is unavailable.
dind_bridge_ns=$(readlink /proc/self/ns/net 2>/dev/null) || dind_bridge_ns=
dind_bridge_base=$(cat ${shellQuote(baseNetnsFile)} 2>/dev/null) || dind_bridge_base=
dind_bridge_name=
if [ -z "$dind_bridge_base" ]; then
  echo 'dind-bridge: serve is not running; Docker is unavailable' >&2
elif [ -n "$dind_bridge_ns" ] && [ "$dind_bridge_ns" != "$dind_bridge_base" ]; then
  dind_bridge_name="@${namePrefix}-$(id -u)-${instance}-$(printf '%s' "$dind_bridge_ns" | tr -cd 0-9)"
  if ! grep -q -e " $dind_bridge_name\\$" /proc/self/net/unix 2>/dev/null; then
    ${ensure} >/dev/null ||
      echo 'dind-bridge: relay unavailable; running without Docker access' >&2
  fi
fi
unset dind_bridge_ns dind_bridge_base dind_bridge_name
`;
}
